apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-appl-db-depl
spec:
  selector:
    matchLabels:
      app: job-appl-db
  template:
    metadata:
      labels:
        app: job-appl-db
    spec:
      containers:
        - name: job-application-db-cont
          image: mongo:6

          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "128Mi"
              cpu: "500m"

          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
          ports:
            - containerPort: 27017

      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: job-appl-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: job-appl-db-serv
spec:
  selector:
    app: job-appl-db
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP
