apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: job-appl-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: standard