apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.back.name }}-depl
  labels:
    app: {{ .Values.back.name }}

  {{- if .Values.namespace.namespaceSeparation }}
  namespace: {{.Values.namespace.name}}
  {{- end}}

spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.front.replicaCount }}
  {{- end }}

  selector:
    matchLabels:
      app: {{ .Values.back.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.back.name }}
    spec:
      containers:
        - name: {{ .Values.back.name }}-cont
          image: {{ .Values.back.image }}
          ports:
            - containerPort: {{ .Values.back.containerPort }}
          
          {{- with .Values.front.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          envFrom:
            - configMapRef:
                name: {{ .Values.back.name }}-confmap
            - secretRef:
                name: {{ .Values.back.name }}-secret
