apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}-serv
  labels:
    app: {{ .Values.db.name }}

  {{- if .Values.namespace.namespaceSeparation }}
  namespace: {{.Values.namespace.name}}
  {{- end}}

spec:
  type: {{ .Values.db.service.type }}
  selector:
    app: {{ .Values.db.name }}
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.targetPort }}
