apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.front.name }}-depl

  {{- if .Values.namespace.namespaceSeparation }}
  namespace: {{.Values.namespace.name}}
  {{- end}}
  
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.front.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.front.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.front.name }}
    spec:
      containers:
        - name: {{ .Values.front.name }}-cont
          image: {{ .Values.front.image }}
          ports:
            - containerPort: {{ .Values.front.cont_port }}

          {{- with .Values.front.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          env:
            {{- range $key, $value := .Values.front.env }}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.front.name }}-confmap
                  key: {{ $key }}
            {{- end }}

          volumeMounts:
            - name: frontend-config
              mountPath: /usr/share/nginx/html/config.json
              subPath: config.json

      volumes:
        - name: frontend-config
          configMap:
            name: {{ .Values.front.name }}-confmap
